CALL_ME_LEADER_TIMEOUT = 5
ELECTION_RESET_TIMEOUT = 5
LEADER_PING_TIMEOUT = 5
PING_INTERVAL = 5
INFORM_INTERVAL = 5
CHECK_LEADER_INTERVAL = 10
COLORS_CHECK_INTERVAL = 10 # must be higher than ALIVE_TIMEOUT!

SERVER_PORT = 12345

GREEN_COLOR_REQUIRED = 1/3
ALIVE_TIMEOUT = 3